version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/images/php/8.2/Dockerfile
        container_name: laravel_console_app
        volumes:
            - ./:/app
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_laravel
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
